import Link from "next/link";
import { getSEOTags } from "@/libs/seo";
import config from "@/config";

// CHATGPT PROMPT TO GENERATE YOUR TERMS & SERVICES — replace with your own data 👇

// 1. Go to https://chat.openai.com/
// 2. Copy paste bellow
// 3. Replace the data with your own (if needed)
// 4. Paste the answer from ChatGPT directly in the <pre> tag below

// You are an excellent lawyer.

// I need your help to write a simple Terms & Services for my website. Here is some context:
// - Website: https://chatsa.co
// - Name: Chatsa
// - Contact information: mohsinb.alshammari@gmail.com
// - Description: A JavaScript code boilerplate to help entrepreneurs launch their startups faster
// - Ownership: when buying a package, users can download code to create apps. They own the code but they do not have the right to resell it. They can ask for a full refund within 7 day after the purchase.
// - User data collected: name, email and payment information
// - Non-personal data collection: web cookies
// - Link to privacy-policy: https://chatsa.co/privacy-policy
// - Governing Law: France
// - Updates to the Terms: users will be updated by email

// Please write a simple Terms & Services for my site. Add the current date. Do not add or explain your reasoning. Answer:

export const metadata = getSEOTags({
  title: `Terms and Conditions | ${config.appName}`,
  canonicalUrlRelative: "/tos",
});

const TOS = () => {
  return (
    <main className="max-w-xl mx-auto">
      <div className="p-5">
        <Link href="/" className="btn btn-ghost">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="currentColor"
            className="w-5 h-5"
          >
            <path
              fillRule="evenodd"
              d="M15 10a.75.75 0 01-.75.75H7.612l2.158 1.96a.75.75 0 11-1.04 1.08l-3.5-3.25a.75.75 0 010-1.08l3.5-3.25a.75.75 0 111.04 1.08L7.612 9.25h6.638A.75.75 0 0115 10z"
              clipRule="evenodd"
            />
          </svg>
          Back
        </Link>
        <h1 className="text-3xl font-extrabold pb-6">
          Terms and Conditions for {config.appName}
        </h1>

        <pre
          className="leading-relaxed whitespace-pre-wrap"
          style={{ fontFamily: "sans-serif" }}
        >
          {`Last Updated: March 20, 2024

Welcome to Chatsa!

These Terms of Service ("Terms") govern your use of the Chatsa website at https://chatsa.co ("Website") and our AI chatbot services. By using our Website and services, you agree to these Terms.

1. Description of Service

Chatsa is an AI chatbot platform that allows businesses to create custom chatbots trained on their knowledge base. Our platform helps you build conversational AI that understands your specific business context.

2. Ownership and Usage Rights

When you subscribe to Chatsa, you gain access to our AI chatbot platform and related services. While you own the content you provide and the conversations generated by your chatbot, the underlying technology and platform remain the property of Chatsa. We offer a full refund within 7 days of purchase if you're not satisfied with our service.

3. Data and Privacy

3.1 User Data
We collect and store user data, including name, email, and payment information, as necessary to provide our services.

3.2 Knowledge Base Data
Any content you provide to train your chatbot is treated as confidential. We use this data solely for training your specific chatbot and improving our services.

For complete details on how we handle your data, please refer to our Privacy Policy at https://chatsa.co/privacy-policy.

4. Service Usage

4.1 Acceptable Use
You agree to use our service in compliance with all applicable laws and regulations. You may not:
- Use the service for any illegal purposes
- Upload malicious content or malware
- Attempt to reverse engineer the platform
- Share your account credentials

4.2 Content Guidelines
You are responsible for ensuring that your knowledge base content:
- Does not violate any intellectual property rights
- Is accurate and up-to-date
- Does not contain harmful or discriminatory content

5. Governing Law

These Terms are governed by the laws of Saudi Arabia.

6. Updates to the Terms

We may update these Terms from time to time. Users will be notified of any changes via email.

For any questions or concerns regarding these Terms of Service, please contact us at mohsinb.alshammari@gmail.com.

Thank you for using Chatsa!`}
        </pre>
      </div>
    </main>
  );
};

export default TOS;
