name = "vectorize-worker"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[build]
command = "npm install && npm run build"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "chatbot-vectors"
dimensions = 768
metric = "cosine" 